# Generated by Django 5.1.3 on 2024-11-15 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tilavaraus', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='kayttaja',
            name='rooli',
            field=models.CharField(choices=[('user', 'User'), ('admin', 'Admin')], default='user', max_length=10),
        ),
    ]
