# Generated by Django 5.1.3 on 2024-11-15 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tilavaraus', '0002_kayttaja_rooli'),
    ]

    operations = [
        migrations.AddField(
            model_name='kayttaja',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='kayttaja',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='kayttaja',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AddField(
            model_name='kayttaja',
            name='password',
            field=models.CharField(default='salasana', max_length=128, verbose_name='password'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='kayttaja',
            name='nimi',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='kayttaja',
            name='rooli',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterModelTable(
            name='kayttaja',
            table=None,
        ),
    ]
