# Generated by Django 5.1.3 on 2024-11-15 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tilavaraus', '0004_alter_kayttaja_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kayttaja',
            name='salasana',
        ),
    ]
