# Generated by Django 5.1.3 on 2024-11-14 10:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kayttaja',
            fields=[
                ('tunnus', models.AutoField(primary_key=True, serialize=False)),
                ('nimi', models.CharField(max_length=100)),
                ('salasana', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'kayttajat',
            },
        ),
        migrations.CreateModel(
            name='Tilat',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tilan_nimi', models.CharField(max_length=16)),
            ],
            options={
                'db_table': 'tilat',
            },
        ),
        migrations.CreateModel(
            name='Varaajat',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nimi', models.CharField(max_length=64)),
            ],
            options={
                'db_table': 'varaajat',
            },
        ),
        migrations.CreateModel(
            name='Varaukset',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('varauspaiva', models.DateField()),
                ('tila', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tilavaraus.tilat')),
                ('varaaja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tilavaraus.varaajat')),
            ],
            options={
                'db_table': 'varaukset',
            },
        ),
    ]
